### ISSUE TITLE
Output/link details of clones from stories.Rdata by patient

### ISSUE THREAD

**Issue by annaquaglieri16** [annaquaglieri16/mutexplore#1]
Hey Chris, 

As Ian mentioned, he would like to have the stories details. One option as you said would be to provide the link to the pdfs so not create an extra table. 

Would you create a folder with soft links to the pdfs by patients into /stornext/Genomics/data/AML_RNA/venetoclax_trial/scripts/07-lineplots_app/input_data ? So that I can try to print out the link in the app?

Thanks!

**Comment by ChristofferFlensburg** [comment]
i made a subdirectory "riverLinks" with softlinks to the rivers. Formated like D32-river.pdf.

Is that easy for you to add to the plot?

**Comment by annaquaglieri16** [comment]
Will try! I think it should be ok, or have a go if you want to!

**Comment by annaquaglieri16** [comment]
We decided that when someone is exploring the app they could simply open up the PDF relative to the river plots for the patient of interest.
